// Code generated by protoc-gen-go. DO NOT EDIT.
// source: def.proto

package def

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListenerID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenerID) Reset()         { *m = ListenerID{} }
func (m *ListenerID) String() string { return proto.CompactTextString(m) }
func (*ListenerID) ProtoMessage()    {}
func (*ListenerID) Descriptor() ([]byte, []int) {
	return fileDescriptor_76fb0470a3b910d8, []int{0}
}

func (m *ListenerID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenerID.Unmarshal(m, b)
}
func (m *ListenerID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenerID.Marshal(b, m, deterministic)
}
func (m *ListenerID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenerID.Merge(m, src)
}
func (m *ListenerID) XXX_Size() int {
	return xxx_messageInfo_ListenerID.Size(m)
}
func (m *ListenerID) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenerID.DiscardUnknown(m)
}

var xxx_messageInfo_ListenerID proto.InternalMessageInfo

func (m *ListenerID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Message struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_76fb0470a3b910d8, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Request struct {
	Listener             *ListenerID `protobuf:"bytes,1,opt,name=listener,proto3" json:"listener,omitempty"`
	Topic                string      `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_76fb0470a3b910d8, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetListener() *ListenerID {
	if m != nil {
		return m.Listener
	}
	return nil
}

func (m *Request) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func init() {
	proto.RegisterType((*ListenerID)(nil), "ListenerID")
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*Request)(nil), "Request")
}

func init() {
	proto.RegisterFile("def.proto", fileDescriptor_76fb0470a3b910d8)
}

var fileDescriptor_76fb0470a3b910d8 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x49, 0x4d, 0xd3,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x92, 0xe1, 0xe2, 0xf2, 0xc9, 0x2c, 0x2e, 0x49, 0xcd, 0x4b,
	0x2d, 0xf2, 0x74, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x62, 0xca, 0x4c, 0x51, 0x92, 0xe5, 0x62, 0xf7, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0x12,
	0xe2, 0x62, 0x49, 0xca, 0x4f, 0xa9, 0x84, 0x4a, 0x82, 0xd9, 0x4a, 0x1e, 0x5c, 0xec, 0x41, 0xa9,
	0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0xea, 0x5c, 0x1c, 0x39, 0x50, 0x73, 0xc0, 0x4a, 0xb8, 0x8d,
	0xb8, 0xf5, 0x10, 0x06, 0x07, 0xc1, 0x25, 0x85, 0x44, 0xb8, 0x58, 0x4b, 0xf2, 0x0b, 0x32, 0x93,
	0x25, 0x98, 0xc0, 0x06, 0x41, 0x38, 0x46, 0x31, 0x5c, 0x5c, 0xc1, 0xa5, 0x49, 0xc5, 0xc9, 0x45,
	0x99, 0x49, 0xa9, 0x45, 0x42, 0x2a, 0x5c, 0x3c, 0x50, 0x73, 0x43, 0x40, 0xb2, 0x42, 0x1c, 0x7a,
	0x50, 0xae, 0x14, 0x87, 0x1e, 0xd4, 0x3d, 0x4a, 0x0c, 0x42, 0x1a, 0x5c, 0xdc, 0x10, 0x1b, 0x20,
	0x8a, 0x90, 0xed, 0x43, 0x56, 0x67, 0xc0, 0x98, 0xc4, 0x06, 0xf6, 0xab, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0xea, 0x52, 0x5c, 0x27, 0xf8, 0x00, 0x00, 0x00,
}
